#========================================server config=====================================
server:
  port: 9300
#========================================spring config=====================================
spring:
  application:
    name: seata-springcloud-storage
  devtools:
    restart:
      enabled: false
#========================================MySQL config=====================================
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/fescardb?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT%2B8
    url: jdbc:mysql://localhost:3306/seata?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT%2B8
    #url: jdbc:mysql://localhost:3306/seata-stor-db?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT%2B8
    #url: jdbc:mysql://10.14.8.232:3306/baojun_app?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: andy123L
    #password: Sgmw@5050
#========================================mybatis config=====================================
mybatis:
  type-aliases-package: com.sly.seata.common.model
  mapper-locations: classpath:mapper/*.xml
#========================================eureka config=====================================
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
